name: Build  


on: 
  push:
    branches:
    - main
    - update-tfc-backend
  workflow_dispatch: 
    inputs: 
      workflow2_name: 
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Deploy'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'hashicorp'   

      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'immutable-infrastructure'

jobs: 
  build: 
    name: Run web app
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{secrets.G_ACCESS_TOKEN}}
      
    steps: 
      
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Deploy Web App 
        run: | 
          cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Deploy Web App"
          sleep 10s
      - name: Deploy Web App 
        run: | 
          cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
          python $GITHUB_WORKSPACE/Deployment-Scripts/workflow_trigger.py
          ${{ env.pat_token }} 
          ${{ github.event.inputs.workflow2_github_account }}  
          ${{ github.event.inputs.workflow2_repo_github }} 
          ${{ github.event.inputs.workflow2_name}}   


